name: Build and Test

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      TAG: "0.16.0"
      SHA: "c34ba943c30abdf48aa818a138dbcd8a81e6b8f6"
    steps:
     - name: Checkout
       uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
       with:
         ref: ${{ github.ref }}

     - name: Setup just
       run: sudo snap install --edge --classic just

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
     
     - name: Install AWSCLI
       run: |
         pip install awscli

     - name: Clone ArmoniK.Core repository
       run: |
            git clone https://github.com/aneoconsulting/armonik.core
            cd armonik.core
            git checkout $SHA

     - name: Build Docker images
       run: |
          docker build --build-arg IMAGE=dockerhubaneo/armonik_pollingagent:$TAG -t pollingagentplugin:$TAG -f ./PollingAgent/Dockerfile .
          docker build --build-arg IMAGE=dockerhubaneo/armonik_control:$TAG -t submitterplugin:$TAG -f ./Submitter/Dockerfile .

     - name: Set environment variables and deploy Core
       working-directory: armonik.core
       run: |
          export POLLING_AGENT_IMAGE="pollingagentplugin"
          export SUBMITTER_IMAGE="submitterplugin"
          export TF_VAR_custom_env_vars='{ "Components__QueueAdaptorSettings__ClassName" = "ArmoniK.Contrib.Plugin.SimpleAmqp.QueueBuilder", "Components__QueueAdaptorSettings__AdapterAbsolutePath" = "/adapters/queue/simpleamqp/ArmoniK.Contrib.Plugin.SimpleAmqp.dll" }'
          just tag=$TAG deploy

     - name: Check the value of adapter path
       run: |
         export CHECK=$(docker inspect armonik.control.submitter | jq '.[0].Config.Env[] | select(startswith("Components__QueueAdaptorSettings__AdapterAbsolutePath=")) | . == "Components__QueueAdaptorSettings__AdapterAbsolutePath=/adapters/queue/simpleamqp/ArmoniK.Contrib.Plugin.SimpleAmqp.dll"')
         if [ $CHECK != "true" ]; then
           echo "The adapter path does not match the expected path"
           exit 1
         else
           echo "The adapter path matches the expected path"
         fi

     - name: Run htcMock test 100 tasks 1 level
       timeout-minutes: 3
       run: |
          docker run --net armonik_network --rm \
            -e HtcMock__NTasks=100 \
            -e HtcMock__TotalCalculationTime=00:00:00.100 \
            -e HtcMock__DataSize=1 \
            -e HtcMock__MemorySize=1 \
            -e HtcMock__SubTasksLevels=1 \
            -e HtcMock__Partition=TestPartition0 \
            -e GrpcClient__Endpoint=http://armonik.control.submitter:1080 \
            dockerhubaneo/armonik_core_htcmock_test_client:$TAG

     - name: Show logs
       if: always()
       working-directory: armonik.core
       run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          tar -czf - terraform/logs/armonik-logs.json | aws s3 cp - s3://${{ secrets.AWS_LOG_BUCKET_NAME }}/plugin-pipeline/${{ github.run_number }}/${{ github.run_attempt }}/plugin-logs.json.tar.gz

  